### ISSUE TITLE
Rename 3.1.9-1 to 3.1.10 or something

### ISSUE THREAD

**Issue by kawauso** [brix/crypto-js#171]
Rename 3.1.9-1 to 3.1.10 or something please!
yarn outdated always complains:
Package               Current Wanted Latest  Package Type    URL                                                                        
crypto-js             3.1.8   3.1.8  3.1.9-1 dependencies    http://github.com/brix/crypto-js       
even after yarn upgrade.

**Comment by pilafmon** [comment]
The dash in the number also breaks semantic versioning in **npm**.

**package.json**:

    "crypto-js": "^3.1",

Incorrectly installs **3.1.8** instead of **3.1.9-1** which causes `npm outdated` to flag an outdated dependency.

![outdated](https://user-images.githubusercontent.com/119555/49561400-e3e0a500-f8cb-11e8-95f0-0b2900b56347.png)

**Comment by evanvosberg** [comment]
New version `3.2.0`

**Comment by u01jmg3** [comment]
`npm publish`?

**Comment by evanvosberg** [comment]
https://www.npmjs.com/package/crypto-js

**Comment by evanvosberg** [comment]
Strange UI on npmjs.org web site.

> evanvosberg published 3.2.0 • 2 hours ago

for

https://www.npmjs.com/search?q=crypto-js

---

> 3.1.9-1 • Public • Published 3 years ago

for

https://www.npmjs.com/package/crypto-js

---

But `npm info crypto-js` shows `3.2.0`
