### ISSUE TITLE
Keccak256 (crypto-js sha3) wrong output?

### ISSUE THREAD

**Issue by miguelmota** [brix/crypto-js#223]
The sha3 (keccak256) seems incorrect 

```js
const CryptoJS = require('crypto-js')
const SHA3 = require('crypto-js/sha3')

console.log(SHA3('a').toString(CryptoJS.enc.Hex))
// 9c46dbec5d03f74352cc4a4da354b4e9796887eeb66ac292617692e765dbe400352559b16229f97b27614b51dbfbbb14613f2c10350435a8feaf53f73ba01c7c
```

[Expected](https://emn178.github.io/online-tools/keccak_256.html)

```
3ac225168df54212a25c1c01fd35bebfea408fdac2e31ddd6f80a4bbf9a5f1cb
```

**Comment by brywil** [comment]
Keccak-256 (submitted) is very slightly different from SHA3-256 (specified).  The padding constant was changed.  This could lilkely be fixed in a couple of lines of code and I may get around to submitting a patch one of these days.  You can calculate both online here:  http://emn178.github.io/online-tools/keccak_512.html

**Comment by miguelmota** [comment]
@brywil got it thanks!

**Comment by renleiabc** [comment]
//requires another parameter
const hash1 = CryptoJS.SHA3('a', { outputLength: 256 }).toString();
// 3ac225168df54212a25c1c01fd35bebfea408fdac2e31ddd6f80a4bbf9a5f1cb
