### ISSUE TITLE
How to sign with RSA-SHA1?

### ISSUE THREAD

**Issue by keyiis** [brix/crypto-js#73]
How to use crypto-js to sign string with RSA-SHA1?

**Comment by evanvosberg** [comment]
CryptoJS does not support RSA.

**Comment by runev** [comment]
+1 because [draft-cavage-http-signatures-10](https://datatracker.ietf.org/doc/draft-cavage-http-signatures/) allows message signing with RSA. This is how most European banks will require developers to sign their requests (although with RSA-SHA256, not RSA-SHA1) when communicating with them, since they'll most likely follow Berlin Group's XS2A Framework Implementation Guidelines while creating a PSD2 compliant open banking API.

The fact that crypto-js is the only crypto library available in Postman make it impossible to sign requests properly using a pre-request script. This sort of sucks both for developers and testers, as we've been forced to deploy a custom-written Node.js reverse proxy which only does the http message signing.

So; 

Will CryptoJS ever support RSA, or should I move over to Postman and ask them to find a more complete crypto library for their sandbox?
